name: Python CI

on:
  push:
    branches:
      - master # Run on pushes to the main branch
  pull_request:
    branches:
      - master # Run on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # The type of runner that the job will execute on

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Set up Docker Buildx (for multi-platform builds, good practice)
      uses: docker/setup-buildx-action@v3

#     - name: Login to Docker Hub (Optional, if you push images to Docker Hub)
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t my_image_name .

    - name: Run tests inside Docker container
      run: |
        # If only using Dockerfile (adjust 'my_image_name' and '/app' to your setup):
        docker run --rm -v $(pwd):/app -w /app my_image_name pytest tests/
        # --rm: remove container after exit
        # -v $(pwd):/app: Mount current host directory to /app in container
        # -w /app: Set working directory inside container to /appx